### ISSUE TITLE
Can not run for Structured Pruning!

### ISSUE THREAD

**Issue by Miocio-nora** [INCHEON-CHO/Dynamic-Pruning-with-Feedback#4]
I found lots of issues while running with the setting of structured pruning.
1) in file main.py, line 247:
> 
        if args.prune:
            if (globals()['iterations']+1) % args.prune_freq==0 and (epoch+1) <= args.milestones[1]:
                target_sparsity = args.prune_rate - args.prune_rate * (1 - (globals()['iterations'])/(args.milestones[1] * len(train_loader)))**3
                if args.prune_type == 'structured':
                    filter_mask = pruning.get_filter_mask(model, rate, args)
                    pruning.filter_prune(model, filter_mask)
>
where 'rate' in 'filter_mask = pruning.get_filter_mask(model, rate, args)' should be replaced with 'target_sparsity'. This is not a big problem. But, after I fixed this, the following issue occurred:

2) line 78, in filter_prune

> 
        ===> [ Training ]
        Epoch: [0][  0/391]     Time  0.608 ( 0.608)    Data  0.089 ( 0.089)    Loss 2.5386e+00 (2.5386e+00)    Acc@1  12.50 ( 12.50)   Acc@5  51.56 ( 51.56)
        Traceback (most recent call last):
          File "main.py", line 336, in <module>
            main(args)
          File "main.py", line 130, in main
            acc1_train, acc5_train = train(args, train_loader,
          File "main.py", line 248, in train
            pruning.filter_prune(model, filter_mask)
          File "/home/mio/MY_Projects/DPM Decay Pruning Method/dynamic feedback        pruning/Dynamic_Model_Pruning_with_Feedback/pruning/utils.py", line 78, in filter_prune
            item.data[i,:,:,:] = 1 if filter_mask[idx] else 0
        IndexError: index 64 is out of bounds for axis 0 with size 64

> 
where:
> 
        def filter_prune(model, filter_mask):
            idx = 0
            for name, item in model.module.named_parameters():
                if len(item.size())==4 and 'mask' in name:
                    for i in range(item.size(0)):
                        item.data[i,:,:,:] = 1 if filter_mask[idx] else 0
                        idx+=1
> 
How can I fix this bug to run for structured pruning mode?

**Comment by Miocio-nora** [comment]
Problem solved!!!
The function get_filter_mask(), Line 67 in file utils.py:
`    filter_mask = np.greater(importance, threshold)`
should be:
`    filter_mask = np.greater(importance_all, threshold)`
